# -*- coding: utf-8 -*-
"""Breadboard _layout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hANyAqNruzoj22uIsecBooDWwp4nV2p
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import os # Import the os module

fig, ax = plt.subplots(figsize=(12, 6))
ax.set_xlim(0, 60)
ax.set_ylim(0, 20)
ax.set_aspect('equal')
ax.axis('off')

# --- Draw breadboard body ---
board = patches.FancyBboxPatch((0, 0), 60, 20, boxstyle="round,pad=0.3",
                                linewidth=1, edgecolor='gray', facecolor='#f0ecd8')
ax.add_patch(board)

# --- Power rails (top and bottom strips) ---
for y_center, label in [(18, '+ / - rail (top)'), (2, '+ / - rail (bottom)')]:
    ax.text(1, y_center + 0.7, label, fontsize=7, color='dimgray')
    for x in range(3, 58, 1):
        color = 'red' if (x % 2 == 0) else 'blue'
        ax.plot(x, y_center, 'o', markersize=2, color=color, alpha=0.5)

# --- Main terminal strip holes (rows of 5, two halves split by center gap) ---
for row in range(5, 16):  # 11 rows
    for col in range(5, 55):
        if 28 <= col <= 31:  # center divider
           continue
        ax.plot(col, row, 'o', markersize=1.5, color='gray', alpha=0.4)

# --- Helper to label/draw a component box ---
def add_component(x, y, w, h, label, color):
    box = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1",
                                  linewidth=1.2, edgecolor='black',
facecolor=color, alpha=0.85)
    ax.add_patch(box)
    ax.text(x + w / 2, y + h / 2, label, ha='center', va='center', fontsize=7, weight='bold')

# --- Place components along the signal path ---
add_component(8, 10, 4, 3, 'Photodiode', '#ffb3a7')      # photodiode
add_component(15, 9, 6, 5, 'Op-amp\n(TIA)', '#a7d8d8')    # op-amp DIP package
add_component(24, 11, 2, 1.2, 'Rf', '#fcdf9f')            # feedback resistor
add_component(24, 8.5, 2, 1.2, 'Cf', '#fcdf9f')           # feedback capacitor
add_component(33, 9, 5, 4, 'RC filter\n(anti-alias)', '#d8c7f0')
add_component(40, 9, 8, 4, 'ADC\n(MCP3008/ADS1115)', '#c7e0f0')
add_component(50, 14, 8, 4, 'To Raspberry Pi\n(SPI/I2C header)', '#cfe8c0')

# --- Wires (simple straight connecting lines between component centers) ---
wire_points = [
    ((12, 11.5), (15, 11.5)),   # photodiode -> op-amp
    ((21, 11.5), (24, 11.6)),   # op-amp -> Rf
    ((26, 11.6), (33, 11)),     # Rf -> RC filter
    ((38, 11), (40, 11)),       # RC filter -> ADC
    ((48, 11), (54, 14)),       # ADC -> Pi
    ]
for (x1, y1), (x2, y2) in wire_points:
    ax.plot([x1, x2], [y1, y2], color='darkred', linewidth=1.5)
# --- Ground wire (dashed, runs along the bottom rail) ---
ax.plot([10, 10, 54, 54], [10, 2.5, 2.5, 14], linestyle='--', color='black', linewidth=1, alpha=0.6)
ax.text(30, 1.3, 'Shared ground rail', fontsize=7, color='black', ha='center')

ax.set_title('Breadboard layout: photodiode -> TIA -> filter -> ADC -> Raspberry Pi', fontsize=11)
plt.tight_layout()

# Ensure the output directory exists
output_dir = '/mnt/user-data/outputs/'
os.makedirs(output_dir, exist_ok=True)

plt.savefig(os.path.join(output_dir, 'breadboard_layout.png'), dpi=200, bbox_inches='tight')
plt.show()

print("Breadboard layout saved.")