# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9iHcXudYz6hmjuZyQ7thO9iw4i1AjRd
"""

import numpy as np
import matplotlib.pyplot as plt

"""## creating arrays in numpy"""

a1 = np.array([2,4,6,8])
a1